//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FFRend.rc
//
#define IDR_MAINFRAME                   101
#define IDR_FB_CTX_BAR                  102
#define IDR_FB_CTX_ITEM                 103
#define IDR_FFRENDTYPE                  104
#define IDR_HISTORY_CTX                 105
#define IDR_JOB_CONTROL                 106
#define IDR_JOB_CONTROL_CTX             107
#define IDR_MAIN_JOB                    108
#define IDR_METAPARM_CTX                109
#define IDR_PLAYLIST                    110
#define IDR_PLAYLIST_CTX                111
#define IDR_VIEW_CTX                    112
#define IDR_VIEW_ROW_CTX                113
#define IDI_FF_HDR_PLAY                 114
#define IDI_MONITOR                     115
#define IDI_PL_LOOPD                    116
#define IDI_PL_LOOPU                    117
#define IDI_PL_NORMAL                   118
#define IDI_PL_PLAYD                    119
#define IDI_PL_PLAYING                  120
#define IDI_PL_PLAYU                    121
#define IDI_PL_SHUFFLED                 122
#define IDI_PL_SHUFFLEU                 123
#define IDI_PL_STOPPED                  124
#define IDI_SORT_DOWN                   125
#define IDI_SORT_UP                     126
#define IDD_ABOUTBOX                    127
#define IDD_ADV_ENGINE_OPTS             128
#define IDD_FF_PLUGS_ROW                129
#define IDD_FILE_SEARCH_DLG             130
#define IDD_JOB_CONTROL                 131
#define IDD_LOAD_BALANCE_ROW            132
#define IDD_MASTER                      133
#define IDD_METAPARM_GROUP              134
#define IDD_METAPARM_PROPS              135
#define IDD_METAPARM_ROW                136
#define IDD_METAPLUG_DEFAULTS           137
#define IDD_METAPLUG_PROPS              138
#define IDD_MIDI_SETUP                  139
#define IDD_MIDI_SETUP_ROW              140
#define IDD_MISSING_FILES_DLG           141
#define IDD_MSG_BOX                     142
#define IDD_MULTI_FILE                  143
#define IDD_OPTS_ENGINE                 144
#define IDD_OPTS_MIDI                   145
#define IDD_OPTS_VIEW                   146
#define IDD_PATCH_ROW                   147
#define IDD_PLAYLIST                    148
#define IDD_PROGRESS                    149
#define IDD_RECORD                      150
#define IDD_REC_STAT                    151
#define IDD_REPLACE_FILES_DLG           152
#define IDD_ROW_FORM                    153
#define IDD_SHUTDOWN_WARN               154
#define IDD_SLIDER_SELECTION            155
#define IDS_APP_ABOUT_TEXT              200
#define IDS_APP_LICENSE                 201
#define IDS_AVI_FILTER                  202
#define IDS_BITMAP_FILTER               203
#define IDS_BTAE_CREATE_MUX             204
#define IDS_CBT_FILE_BROWSER            205
#define IDS_CBT_GRAPH                   206
#define IDS_CBT_HISTORY                 207
#define IDS_CBT_LOAD_BALANCE            208
#define IDS_CBT_MASTER                  209
#define IDS_CBT_METAPARM                210
#define IDS_CBT_MIDI_SETUP              211
#define IDS_CBT_MONITOR                 212
#define IDS_CBT_PARAM                   213
#define IDS_CBT_PATCH                   214
#define IDS_CBT_QUEUE                   215
#define IDS_DOCKABLE                    216
#define IDS_DOC_BAD_FORMAT              217
#define IDS_EDIT_REDO_FMT               218
#define IDS_EDIT_UNDO_FMT               219
#define IDS_ENGERR_CANT_CREATE_EVENT    220
#define IDS_ENGERR_CANT_CREATE_QUEUE    221
#define IDS_ENGERR_CANT_CREATE_THREAD   222
#define IDS_ENGERR_CANT_INIT_THREAD     223
#define IDS_ENGERR_CANT_START_THREAD    224
#define IDS_ENGERR_CANT_STOP_RENDERER   225
#define IDS_ENGERR_CANT_STOP_THREAD     226
#define IDS_ENGERR_CANT_WRITE_QUEUE     227
#define IDS_ENGERR_NEED_PROCESS_COPY    228
#define IDS_ENGERR_SUCCESS              229
#define IDS_FB_CLIPS                    230
#define IDS_FB_COL_MODIFIED             231
#define IDS_FB_COL_NAME                 232
#define IDS_FB_COL_SIZE                 233
#define IDS_FB_COL_TYPE                 234
#define IDS_FB_FILE_SUFFIX              235
#define IDS_FB_PLUGINS                  236
#define IDS_FB_PROJECTS                 237
#define IDS_FFERR_BAD_PETE_PLUGIN       238
#define IDS_FFERR_CANT_GET_PARAM_NAME   239
#define IDS_FFERR_CANT_GET_PLUGIN_INFO  240
#define IDS_FFERR_CANT_GET_PLUGIN_NAME  241
#define IDS_FFERR_CANT_INSTANTIATE      242
#define IDS_FFERR_CANT_LOAD_PLUGIN      243
#define IDS_FFERR_UNSUPP_BIT_DEPTH      244
#define IDS_FF_CANT_LOAD_PLUGIN         245
#define IDS_FF_CANT_READ                246
#define IDS_FF_CANT_WRITE               247
#define IDS_FF_CAPTION_MOD_RANGE        248
#define IDS_FF_INPUT_DEFAULT            249
#define IDS_FF_INPUT_NONE               250
#define IDS_FF_MOD_ENAB                 251
#define IDS_FF_MOD_FREQ                 252
#define IDS_FF_MOD_PW                   253
#define IDS_FF_MOD_WAVE                 254
#define IDS_FF_PARM_EDIT                255
#define IDS_FF_PARM_NAME                256
#define IDS_FF_PARM_SLIDER              257
#define IDS_FF_PLUG_ABOUT               258
#define IDS_FF_PLUG_CAP_16BIT           259
#define IDS_FF_PLUG_CAP_24BIT           260
#define IDS_FF_PLUG_CAP_32BIT           261
#define IDS_FF_PLUG_CAP_COPYINPLACE     262
#define IDS_FF_PLUG_CAP_MAXFRAMES       263
#define IDS_FF_PLUG_CAP_MINFRAMES       264
#define IDS_FF_PLUG_CAP_NO              265
#define IDS_FF_PLUG_CAP_PREF_BOTH       266
#define IDS_FF_PLUG_CAP_PREF_COPY       267
#define IDS_FF_PLUG_CAP_PREF_INPLACE    268
#define IDS_FF_PLUG_CAP_PREF_NONE       269
#define IDS_FF_PLUG_CAP_PROCESSCOPY     270
#define IDS_FF_PLUG_CAP_YES             271
#define IDS_FF_PLUG_DESCRIP             272
#define IDS_FF_PLUG_PROPS               273
#define IDS_FF_PROPERTIES               274
#define IDS_GRAPH_CANT_GET_OBJECT       275
#define IDS_GRAPH_CANT_OPEN_PICTURE     276
#define IDS_GRAPH_CANT_RUN_DOT          277
#define IDS_GRAPH_DOT_TIMEOUT           278
#define IDS_HISTORY_FILTER              279
#define IDS_HLINK_CANT_LAUNCH           280
#define IDS_JOB_ABORTED                 281
#define IDS_JOB_DEST                    282
#define IDS_JOB_DONE                    283
#define IDS_JOB_END                     284
#define IDS_JOB_FAILED                  285
#define IDS_JOB_FILE_CORRUPT            286
#define IDS_JOB_FILTER                  287
#define IDS_JOB_LOAD_LIST               288
#define IDS_JOB_NAME                    289
#define IDS_JOB_POSTPONED               290
#define IDS_JOB_RUNNING                 291
#define IDS_JOB_SAVE_LIST               292
#define IDS_JOB_SOURCE                  293
#define IDS_JOB_START                   294
#define IDS_JOB_STATUS                  295
#define IDS_JOB_STOPPED_ERROR           296
#define IDS_JOB_WAITING                 297
#define IDS_LBR_CPU_PERCENT             298
#define IDS_LBR_CPU_TIME                299
#define IDS_LBR_PLUGIN_NAME             300
#define IDS_LBR_THREAD_COUNT            301
#define IDS_METAPARM_GROUP              302
#define IDS_METAPARM_NAME               303
#define IDS_METAPARM_NO_PARM_NAME       304
#define IDS_METAPARM_PP_MOD_ENAB        305
#define IDS_METAPARM_PP_MOD_FREQ        306
#define IDS_METAPARM_PP_MOD_PW          307
#define IDS_METAPARM_PP_MOD_WAVE        308
#define IDS_METAPARM_PROP_SUFFIX        309
#define IDS_METAPARM_TARG_CAP_PARM      310
#define IDS_METAPARM_TARG_CAP_PLUG      311
#define IDS_METAPARM_TARG_CAP_PROP      312
#define IDS_METAPARM_TARG_CAP_TYPE      313
#define IDS_METAPARM_UNASSIGNED         314
#define IDS_META_BAD_FORMAT             315
#define IDS_META_BASE_NOT_FOUND         316
#define IDS_META_CANT_CREATE_DIR        317
#define IDS_META_CANT_CREATE_PLUGIN     318
#define IDS_META_CANT_DEFLATE           319
#define IDS_META_CANT_EMBED             320
#define IDS_META_CANT_INFLATE           321
#define IDS_META_CANT_OPEN              322
#define IDS_META_EXPORT                 323
#define IDS_META_IMPORT                 324
#define IDS_META_MISSING_PLUGINS        325
#define IDS_META_NO_APP_FOLDER          326
#define IDS_META_NO_PLUGIN_NAME         327
#define IDS_META_PLUGS_EMBEDDED         328
#define IDS_META_PLUGS_LINKED           329
#define IDS_META_ZLIB_ERROR             330
#define IDS_MF_ABORT_JOBS               331
#define IDS_MF_CANT_ATTACH_MONITOR      332
#define IDS_MF_CANT_CREATE_ENGINE       333
#define IDS_MF_CANT_CREATE_MIDI_DEV     334
#define IDS_MF_CANT_CREATE_RENDERER     335
#define IDS_MF_CANT_DETACH_MONITOR      336
#define IDS_MF_CANT_GET_PROPS           337
#define IDS_MF_CANT_HOOK_KEYBD          338
#define IDS_MF_CANT_OPEN_CLIP           339
#define IDS_MF_CANT_PAUSE_ENGINE        340
#define IDS_MF_CANT_RESUME_ENGINE       341
#define IDS_MF_CANT_SET_EXCLUSIVE       342
#define IDS_MF_CANT_SET_PRIORITY        343
#define IDS_MF_CANT_SHUTDOWN            344
#define IDS_MF_CANT_START_ENGINE        345
#define IDS_MF_CANT_STOP_ENGINE         346
#define IDS_MF_CLIP_PROPS               347
#define IDS_MF_COLOR_DEPTH_MISMATCH     348
#define IDS_MF_ENGINE_STALLED           349
#define IDS_MF_EXPORT                   350
#define IDS_MF_HELP_FILE_MISSING        351
#define IDS_MF_HINT_MONITOR_SOURCE      352
#define IDS_MF_HINT_PLUGIN_INPUT        353
#define IDS_MF_NEED_AVISYNTH            354
#define IDS_MF_OPEN_VIDEO               355
#define IDS_MF_RECORD_AS                356
#define IDS_MF_STOP_RECORD              357
#define IDS_MP_BYPASS                   358
#define IDS_MP_MASTER_SPEED             359
#define IDS_MP_MOD_ENABLE               360
#define IDS_MP_MOD_FREQ                 361
#define IDS_MP_MOD_PW                   362
#define IDS_MP_MOD_WAVE                 363
#define IDS_MP_PARAMETER                364
#define IDS_MS_CHAN                     365
#define IDS_MS_CTRL                     366
#define IDS_MS_EVENT                    367
#define IDS_MS_LEARN                    368
#define IDS_MS_RANGE                    369
#define IDS_MS_TAB_METAPARM             370
#define IDS_MS_TAB_MISC                 371
#define IDS_MS_TAB_PLUGIN               372
#define IDS_MS_VALUE                    373
#define IDS_OPTIONS                     374
#define IDS_OPTS_CUSTOM                 375
#define IDS_OPTS_NO_MIDI_IN             376
#define IDS_OPTS_RESET_ALL              377
#define IDS_OPTS_RESTORE_DEFAULTS       378
#define IDS_OUTPUT                      379
#define IDS_PB_INPUT                    380
#define IDS_PB_SOURCE                   381
#define IDS_PLAYLIST_FILTER             382
#define IDS_PLUGIN_FILTER               383
#define IDS_PL_COL_PROJECT              384
#define IDS_PL_SAVE_CHANGES             385
#define IDS_PROJECT_FILTER              386
#define IDS_REC_CANT_CREATE_BITMAP      387
#define IDS_REC_CANT_CREATE_DC          388
#define IDS_REC_CANT_CREATE_FILTER      389
#define IDS_REC_CANT_CREATE_QUEUE       390
#define IDS_REC_CANT_CREATE_THREAD      391
#define IDS_REC_CANT_GET_SURFACE        392
#define IDS_REC_CANT_HOOK_OUTPUT        393
#define IDS_REC_CANT_QUEUE_UNLIM        394
#define IDS_REC_CANT_SET_SURFACE        395
#define IDS_REC_CANT_START_PLUGIN       396
#define IDS_REC_CANT_START_THREAD       397
#define IDS_REC_CANT_STOP_PLUGIN        398
#define IDS_REC_CANT_STOP_THREAD        399
#define IDS_REC_CANT_UNHOOK_OUTPUT      400
#define IDS_REND_CANT_CREATE_BACKBUF    401
#define IDS_REND_CANT_CREATE_DDRAW      402
#define IDS_REND_CANT_CREATE_SURFACE    403
#define IDS_REND_CANT_CREATE_THREAD     404
#define IDS_REND_CANT_CREATE_TIMER      405
#define IDS_REND_CANT_SET_SURFACE       406
#define IDS_REND_TIMER_WAIT_ERROR       407
#define IDS_RPLF_FILENAME               408
#define IDS_RPLF_MISSING                409
#define IDS_RPLF_REPLACED               410
#define IDS_RPLF_STATUS                 411
#define IDS_UC_BYPASS                   412
#define IDS_UC_CONNECT                  413
#define IDS_UC_COPY                     414
#define IDS_UC_CUT                      415
#define IDS_UC_DELETE                   416
#define IDS_UC_INSERT                   417
#define IDS_UC_INSERT_EMPTY             418
#define IDS_UC_LOAD                     419
#define IDS_UC_LOAD_BALANCE             420
#define IDS_UC_MASTER_SPEED             421
#define IDS_UC_METAPARM_DELETE          422
#define IDS_UC_METAPARM_DRAG            423
#define IDS_UC_METAPARM_GROUP           424
#define IDS_UC_METAPARM_INSERT          425
#define IDS_UC_METAPARM_PROPS           426
#define IDS_UC_METAPARM_UNGROUP         427
#define IDS_UC_METAPARM_VALUE           428
#define IDS_UC_MIDI_SETUP               429
#define IDS_UC_MOD_ENABLE               430
#define IDS_UC_MOD_FREQ                 431
#define IDS_UC_MOD_PW                   432
#define IDS_UC_MOD_RANGE                433
#define IDS_UC_MOD_WAVE                 434
#define IDS_UC_MONITOR_SOURCE           435
#define IDS_UC_MOVE                     436
#define IDS_UC_OPEN_CLIP                437
#define IDS_UC_PARM                     438
#define IDS_UC_PASTE                    439
#define IDS_UC_SELECTION                440
#define IDS_UC_SOLO                     441
#define IDS_UC_SYNC_OSCILLATORS         442
#define IDS_UC_UNLOAD                   443
#define IDS_UPCK_CANT_DOWNLOAD_FILE     444
#define IDS_UPCK_CANT_GET_TEMP_FILE     445
#define IDS_UPCK_CANT_GET_VERSION       446
#define IDS_UPCK_CANT_RUN_INSTALLER     447
#define IDS_UPCK_CANT_UNZIP_DOWNLOAD    448
#define IDS_UPCK_DOWNLOADING_CAPTION    449
#define IDS_UPCK_HAVE_LATEST_VERSION    450
#define IDS_UPCK_SCRIPT_NOT_FOUND       451
#define IDS_UPCK_UPDATE_CANCELED        452
#define IDS_UPCK_WANT_NEWER_VERSION     453
#define IDS_VIDEO_FILTER                454
#define IDS_VIEW_CANT_INSERT_PLUGIN     455
#define IDS_VIEW_CANT_LOAD_PLUGIN       456
#define IDS_VIEW_COL_BYPASS             457
#define IDS_VIEW_COL_COPY_PREF          458
#define IDS_VIEW_COL_DELAY              459
#define IDS_VIEW_COL_INPUTS             460
#define IDS_VIEW_COL_INPUT_A            461
#define IDS_VIEW_COL_PLUGIN             462
#define IDS_VIEW_COL_PROC_COPY          463
#define IDS_VIEW_COL_TYPE               464
#define IDS_VIEW_INSERT_PLUGIN          465
#define IDS_VIEW_LOAD_PLUGIN            466
#define IDS_WAVE_PULSE                  467
#define IDS_WAVE_RAMP_DOWN              468
#define IDS_WAVE_RAMP_UP                469
#define IDS_WAVE_RANDOM                 470
#define IDS_WAVE_RANDOM_RAMP            471
#define IDS_WAVE_SINE                   472
#define IDS_WAVE_SQUARE                 473
#define IDS_WAVE_TRIANGLE               474
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_TEXT                  1002
#define IDC_ABOUT_URL                   1003
#define IDC_AEOP_FRAME_MEMORY_LIMIT     1004
#define IDC_AEOP_FRAME_MEMORY_USED      1005
#define IDC_AEOP_RUN_WHILE_LOADING      1006
#define IDC_DRAG_MULTI                  1007
#define IDC_DRAG_SINGLE                 1008
#define IDC_FB_LIST                     1009
#define IDC_FB_TAB                      1010
#define IDC_FF_MOD_ENAB                 1011
#define IDC_FF_MOD_FREQ                 1012
#define IDC_FF_MOD_FREQ_SPIN            1013
#define IDC_FF_MOD_PW                   1014
#define IDC_FF_MOD_PW_SPIN              1015
#define IDC_FF_MOD_WAVE                 1016
#define IDC_FF_PARM_EDIT                1017
#define IDC_FF_PARM_NAME                1018
#define IDC_FF_PARM_SLIDER              1019
#define IDC_FF_PARM_SPIN                1020
#define IDC_FF_PARM_VIEW                1021
#define IDC_FF_TAB_CTRL                 1022
#define IDC_GRAPH_VIEW                  1023
#define IDC_HISTORY_VIEW                1024
#define IDC_JOB_ABORT                   1025
#define IDC_JOB_DELETE                  1026
#define IDC_JOB_LIST                    1027
#define IDC_JOB_MOVE_DOWN               1028
#define IDC_JOB_MOVE_UP                 1029
#define IDC_JOB_PERCENT                 1030
#define IDC_JOB_POSTPONE                1031
#define IDC_JOB_PROGRESS                1032
#define IDC_JOB_PROG_CAP                1033
#define IDC_JOB_SKIP                    1034
#define IDC_JOB_START                   1035
#define IDC_LBR_CPU_PERCENT_BAR         1036
#define IDC_LBR_CPU_TIME                1037
#define IDC_LBR_PLUGIN_NAME             1038
#define IDC_LBR_THREAD_COUNT_EDIT       1039
#define IDC_LBR_THREAD_COUNT_SPIN       1040
#define IDC_LOAD_BALANCE_VIEW           1041
#define IDC_MA_SPEED_CAP                1042
#define IDC_MA_SPEED_EDIT               1043
#define IDC_MA_SPEED_SLIDER             1044
#define IDC_METAPARM_EDIT               1045
#define IDC_METAPARM_GROUP              1046
#define IDC_METAPARM_NAME               1047
#define IDC_METAPARM_PARAM              1048
#define IDC_METAPARM_PLUGIN             1049
#define IDC_METAPARM_PROP               1050
#define IDC_METAPARM_RANGE_END_EDIT     1051
#define IDC_METAPARM_RANGE_END_SPIN     1052
#define IDC_METAPARM_RANGE_START_EDIT   1053
#define IDC_METAPARM_RANGE_START_SPIN   1054
#define IDC_METAPARM_SLIDER             1055
#define IDC_METAPARM_SPIN               1056
#define IDC_METAPARM_TARG_CAP_PARM      1057
#define IDC_METAPARM_TARG_CAP_PLUG      1058
#define IDC_METAPARM_TARG_CAP_PROP      1059
#define IDC_METAPARM_VIEW               1060
#define IDC_METAPLUG_ABOUT              1061
#define IDC_METAPLUG_DEFAULTS           1062
#define IDC_METAPLUG_DESCRIP            1063
#define IDC_METAPLUG_EDIT_INPUTS        1064
#define IDC_METAPLUG_EMBED              1065
#define IDC_METAPLUG_NAME               1066
#define IDC_METAPLUG_TYPE               1067
#define IDC_METAPLUG_TYPE2              1068
#define IDC_METAPLUG_UNIQUE_ID          1069
#define IDC_METAPLUG_VERSION_MAJOR      1070
#define IDC_METAPLUG_VERSION_MINOR      1071
#define IDC_MIDI_SETUP_VIEW             1072
#define IDC_MISF_OPENDLG                1073
#define IDC_MISF_PROCEED                1074
#define IDC_MONITOR_WND                 1075
#define IDC_MPG_LIST                    1076
#define IDC_MPG_MASTER                  1077
#define IDC_MSG_BOX_ICON                1078
#define IDC_MSG_BOX_TEXT                1079
#define IDC_MS_CHAN                     1080
#define IDC_MS_CHAN_SPIN                1081
#define IDC_MS_CTRL                     1082
#define IDC_MS_CTRL_SPIN                1083
#define IDC_MS_EVENT                    1084
#define IDC_MS_LEARN                    1085
#define IDC_MS_PROP                     1086
#define IDC_MS_RANGE                    1087
#define IDC_MS_RANGE_SPIN               1088
#define IDC_MS_TAB                      1089
#define IDC_MS_TITLE                    1090
#define IDC_MS_VALUE                    1091
#define IDC_MULTI_FILE_PREVIEW          1092
#define IDC_OPTS_ADVANCED               1093
#define IDC_OPTS_CACHE_THUMBS           1094
#define IDC_OPTS_CHECK_FOR_UPDATES      1095
#define IDC_OPTS_COLOR_DEPTH            1096
#define IDC_OPTS_FRAME_HEIGHT           1097
#define IDC_OPTS_FRAME_RATE             1098
#define IDC_OPTS_FRAME_SIZE             1099
#define IDC_OPTS_FRAME_TIMEOUT          1100
#define IDC_OPTS_FRAME_WIDTH            1101
#define IDC_OPTS_HISTORY_SIZE           1102
#define IDC_OPTS_LOCK_FRAME_RATE        1103
#define IDC_OPTS_MIDI_DEV               1104
#define IDC_OPTS_MIDI_REFRESH           1105
#define IDC_OPTS_MONITOR_QUALITY        1106
#define IDC_OPTS_RAND_SEED              1107
#define IDC_OPTS_RAND_USE_TIME          1108
#define IDC_OPTS_SAVE_CHGS_WARN         1109
#define IDC_OPTS_THUMB_SIZE             1110
#define IDC_OPTS_UNDO_LEVELS            1111
#define IDC_OPTS_UNDO_UNLIMITED         1112
#define IDC_OPTS_USE_MM_TIMER           1113
#define IDC_OPTS_VIEW_FREQ              1114
#define IDC_PATCH_VIEW                  1115
#define IDC_PB_ENABLE                   1116
#define IDC_PB_INPUT                    1117
#define IDC_PB_SOURCE                   1118
#define IDC_PL_LIST                     1119
#define IDC_PL_LOOP                     1120
#define IDC_PL_PERIOD_EDIT              1121
#define IDC_PL_PERIOD_SPIN              1122
#define IDC_PL_PLAY                     1123
#define IDC_PL_SHUFFLE                  1124
#define IDC_PROGRESS                    1125
#define IDC_PROGRESS_MSG                1126
#define IDC_PROGRESS_PERCENT            1127
#define IDC_QUEUE_VIEW                  1128
#define IDC_REC_BIT_COUNT               1129
#define IDC_REC_DURATION                1130
#define IDC_REC_DURATION_TYPE           1131
#define IDC_REC_DURATION_TYPE2          1132
#define IDC_REC_DURATION_TYPE3          1133
#define IDC_REC_DURATION_UNIT           1134
#define IDC_REC_DURATION_UNIT2          1135
#define IDC_REC_INP_FRAME_RATE          1136
#define IDC_REC_INP_FRAME_SIZE          1137
#define IDC_REC_OUT_FRAME_HEIGHT        1138
#define IDC_REC_OUT_FRAME_RATE          1139
#define IDC_REC_OUT_FRAME_SIZE          1140
#define IDC_REC_OUT_FRAME_WIDTH         1141
#define IDC_REC_QUEUE_JOB               1142
#define IDC_REC_USE_INP_FRAME_RATE      1143
#define IDC_REC_USE_INP_FRAME_SIZE      1144
#define IDC_RPLF_BROWSE                 1145
#define IDC_RPLF_LIST                   1146
#define IDC_RPLF_SEARCH_ALL             1147
#define IDC_RPLF_SEARCH_FOLDER          1148
#define IDC_RST_ABORT                   1149
#define IDC_RST_DURATION                1150
#define IDC_RST_ELAPSED                 1151
#define IDC_RST_PROGRESS                1152
#define IDC_RST_RECORDED                1153
#define IDC_RST_REMAINING               1154
#define IDC_RST_SHUTDOWN                1155
#define IDC_SLIDER_SEL_END              1156
#define IDC_SLIDER_SEL_START            1157
#define IDC_STATUS                      1158
#define IDC_WARNING_ICON                1159
#define ID_APP_CANCEL                   32771
#define ID_APP_HOME_PAGE                32772
#define ID_EDIT_DELETE                  32773
#define ID_EDIT_INSERT                  32774
#define ID_EDIT_INSERT_EMPTY            32775
#define ID_EDIT_MOD_RANGE_EDIT          32776
#define ID_EDIT_MOD_RANGE_GOTO_END      32777
#define ID_EDIT_MOD_RANGE_GOTO_START    32778
#define ID_EDIT_MOD_RANGE_REMOVE        32779
#define ID_EDIT_MOD_RANGE_SET_END       32780
#define ID_EDIT_MOD_RANGE_SET_START     32781
#define ID_EDIT_OPTIONS                 32782
#define ID_EDIT_PLAYLIST                32783
#define ID_EDIT_SYNC_OSCILLATORS        32784
#define ID_FB_DELETE                    32785
#define ID_FB_FILE_OPEN                 32786
#define ID_FB_FILE_PROPS                32787
#define ID_FB_PARENT_FOLDER             32788
#define ID_FB_RENAME                    32789
#define ID_FB_SORT_DATE                 32790
#define ID_FB_SORT_NAME                 32791
#define ID_FB_SORT_SIZE                 32792
#define ID_FB_SORT_TYPE                 32793
#define ID_FB_VIEW_ICON                 32794
#define ID_FB_VIEW_LIST                 32795
#define ID_FB_VIEW_REPORT               32796
#define ID_FB_VIEW_SMALL_ICON           32797
#define ID_FB_VIEW_THUMBNAIL            32798
#define ID_FILE_EXPORT                  32799
#define ID_FILE_JOB_CONTROL             32800
#define ID_FILE_META_EXPORT             32801
#define ID_FILE_META_IMPORT             32802
#define ID_FILE_META_PROPS              32803
#define ID_FILE_RECORD                  32804
#define ID_FILE_VIDEO_MRU_FILE1         32805
#define ID_FILE_VIDEO_MRU_FILE2         32806
#define ID_FILE_VIDEO_MRU_FILE3         32807
#define ID_FILE_VIDEO_MRU_FILE4         32808
#define ID_FILE_VIDEO_OPEN              32809
#define ID_HELP_CHECK_FOR_UPDATES       32810
#define ID_HISTORY_OPEN                 32811
#define ID_HISTORY_PAUSE                32812
#define ID_HISTORY_SAVE                 32813
#define ID_HISTORY_SHOW_TIMES           32814
#define ID_INDICATOR_ACTUAL_FRAME_RATE  32815
#define ID_INDICATOR_FRAME_SIZE         32816
#define ID_INDICATOR_PAUSE              32817
#define ID_INDICATOR_RECORD             32818
#define ID_INDICATOR_TARGET_FRAME_RATE  32819
#define ID_JOB_EDIT_CLEAR_LIST          32820
#define ID_JOB_EDIT_DELETE              32821
#define ID_JOB_EDIT_DELETE_DONE         32822
#define ID_JOB_EDIT_DONE_WAITING        32823
#define ID_JOB_EDIT_FAILED_WAITING      32824
#define ID_JOB_EDIT_POSTPONE            32825
#define ID_JOB_EDIT_POSTPONED_WAITING   32826
#define ID_JOB_EDIT_SKIP                32827
#define ID_JOB_EDIT_WAITING_POSTPONED   32828
#define ID_JOB_FILE_LOAD_LIST           32829
#define ID_JOB_FILE_SAVE_LIST           32830
#define ID_JOB_OPTS_SHUTDOWN            32831
#define ID_JOB_VIEW_ERROR               32832
#define ID_METAPARM_ADD_ALL_PARAMS      32833
#define ID_METAPARM_ADD_BYPASS          32834
#define ID_METAPARM_ADD_MOD_ENAB        32835
#define ID_METAPARM_ADD_MOD_FREQ        32836
#define ID_METAPARM_ADD_MOD_PW          32837
#define ID_METAPARM_ADD_MOD_WAVE        32838
#define ID_METAPARM_ADD_PARAM           32839
#define ID_METAPARM_DELETE              32840
#define ID_METAPARM_GROUP               32841
#define ID_METAPARM_INSERT              32842
#define ID_METAPARM_PROPS               32843
#define ID_METAPARM_UNGROUP             32844
#define ID_PLUGIN_BYPASS                32845
#define ID_PLUGIN_INPUT                 32846
#define ID_PLUGIN_LOAD                  32847
#define ID_PLUGIN_MONITOR               32848
#define ID_PLUGIN_MRU_FILE1             32849
#define ID_PLUGIN_MRU_FILE2             32850
#define ID_PLUGIN_MRU_FILE3             32851
#define ID_PLUGIN_MRU_FILE4             32852
#define ID_PLUGIN_PROPERTIES            32853
#define ID_PLUGIN_SOLO                  32854
#define ID_PLUGIN_UNLOAD                32855
#define ID_PL_AUTO_LOOP                 32856
#define ID_PL_AUTO_PLAY                 32857
#define ID_PL_AUTO_SHUFFLE              32858
#define ID_PL_EDIT_ADD                  32859
#define ID_PL_EDIT_DELETE               32860
#define ID_PL_EDIT_INSERT               32861
#define ID_PL_EDIT_OPEN_PROJECT         32862
#define ID_PL_FILE_MRU_FILE1            32863
#define ID_PL_FILE_MRU_FILE2            32864
#define ID_PL_FILE_MRU_FILE3            32865
#define ID_PL_FILE_MRU_FILE4            32866
#define ID_PL_FILE_NEW                  32867
#define ID_PL_FILE_OPEN                 32868
#define ID_PL_FILE_SAVE                 32869
#define ID_PL_FILE_SAVE_AS              32870
#define ID_TOOLS_DUMP_STATE             32871
#define ID_TOOLS_FORCE_STALL            32872
#define ID_TOOLS_TEST_REOPEN            32873
#define ID_VIEW_FILES                   32874
#define ID_VIEW_GRAPH                   32875
#define ID_VIEW_HISTORY                 32876
#define ID_VIEW_LOAD_BALANCE            32877
#define ID_VIEW_MASTER                  32878
#define ID_VIEW_METAPARM                32879
#define ID_VIEW_MIDI_SETUP              32880
#define ID_VIEW_MONITOR                 32881
#define ID_VIEW_OUTPUT                  32882
#define ID_VIEW_PATCH                   32883
#define ID_VIEW_QUEUES                  32884
#define ID_VIEW_RECORD_STATUS           32885
#define ID_VIEW_REFRESH                 32886
#define ID_VIEW_RESET_ZOOM              32887
#define ID_VIEW_ZOOM_IN                 32888
#define ID_VIEW_ZOOM_OUT                32889
#define ID_WINDOW_FULL_SCREEN           32890
#define ID_WINDOW_PAUSE                 32891
#define ID_WINDOW_STEP                  32892

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        475
#define _APS_NEXT_COMMAND_VALUE         32893
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
